### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by joey-yoonsung** [scottashipp/mill#13]
Hi. I'm interesting this project for applying it to my project.

The usability of this library is so simple and beautiful.

My project will be a product for my company. The license of this project is MIT, it's not a problem. Before applying it, I want to check do you have willing to maintain this project?( "maintain" means "Can you respond the issue or PR what I request in a week?")

**Comment by scottashipp** [comment]
Thanks for the kind comment! Sorry but it is not maintained in the way you mean. I do review merge requests and respond to comments and issues within a generally reasonable timeframe but this is not guaranteed because I am sometimes traveling and other times do not have the resources to address a given issue within a week. You may be interested in the [StreamX library](https://github.com/amaembo/streamex) for something similar. It seems to be more well-maintained and have more support within the Java ecosystem also.

**Comment by joey-yoonsung** [comment]
@scottashipp Thanks for your answer and suggesting another alternative. Our project cannot use this project. But I got a pretty good insight from your code. Good luck.
